name: Build APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Source Code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Clean Missing Annotations Across Source Files
      run: |
        sed -i '/import android.support.annotation.NonNull;/d' android/app/src/main/java/com/watchcam/*.java
        sed -i 's/@NonNull//g' android/app/src/main/java/com/watchcam/*.java

    - name: Force AndroidX Environment
      run: |
        echo "android.useAndroidX=true" > gradle.properties
        echo "android.enableJetifier=true" >> gradle.properties
      working-directory: android

    - name: Grant Execute Permission for Gradle
      run: chmod +x gradlew
      working-directory: android

    - name: Build Debug APK
      run: ./gradlew clean assembleDebug --no-build-cache
      working-directory: android

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: android/app/build/outputs/apk/debug/app-debug.apk
